"""Telegram integration module."""

from chatfilter.telegram.client import (
    JoinChatError,
    LeaveChatError,
    MessageFetchError,
    SessionFileError,
    TelegramClientLoader,
    TelegramConfig,
    TelegramConfigError,
    get_account_info,
    get_dialogs,
    get_messages,
    get_messages_since,
    get_messages_streaming,
    join_chat,
    join_chat_with_rotation,
    leave_chat,
)
from chatfilter.telegram.rate_limiter import (
    RateLimitConfig,
    TelegramRateLimiter,
    get_rate_limiter,
    set_rate_limiter,
)
from chatfilter.telegram.session_manager import (
    SessionConnectError,
    SessionError,
    SessionInfo,
    SessionInvalidError,
    SessionManager,
    SessionNotConnectedError,
    SessionReauthRequiredError,
    SessionState,
    SessionTimeoutError,
)

__all__ = [
    "JoinChatError",
    "LeaveChatError",
    "MessageFetchError",
    "RateLimitConfig",
    "SessionConnectError",
    "SessionError",
    "SessionFileError",
    "SessionInfo",
    "SessionInvalidError",
    "SessionManager",
    "SessionNotConnectedError",
    "SessionReauthRequiredError",
    "SessionState",
    "SessionTimeoutError",
    "TelegramClientLoader",
    "TelegramConfig",
    "TelegramConfigError",
    "TelegramRateLimiter",
    "get_account_info",
    "get_dialogs",
    "get_messages",
    "get_messages_since",
    "get_messages_streaming",
    "get_rate_limiter",
    "join_chat",
    "join_chat_with_rotation",
    "leave_chat",
    "set_rate_limiter",
]
